version: '3.5'

services:
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: DockerFiles/minio/Dockerfile
    env_file:
      - .env
    volumes:
      - ./volumes/minio:/data/external
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  data_processor:
    container_name: data_processor
    build:
      context: .
      dockerfile: ./DockerFiles/data_processor/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: /entrypoint.sh

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./DockerFiles/backend/Dockerfile
    env_file:
      - .env
    ports:
      - "80:8501"
    volumes:
      - ./backend:/app

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.9
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    env_file:
      - .env
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "data_processor"
      - "etcd"
      - "minio"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.4
    environment:
      MILVUS_URL: milvus:19530
    ports:
      -  "7654:3000"
    depends_on:
      - "milvus"

networks:
  default:
    name: project

